name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: If you expected something else to occur what did you expect?
      placeholder: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: system
    attributes:
      label: What operating system are you using?
      placeholder: operating system
    validations:
      required: true
  - type: textarea
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      placeholder: browsers
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
